<?php 
				echo '<div id="menu-glowne">';
				echo '<a href="strefa-czyszczenia/strefa-czyszczenia-index.php"><div class="ss">STREFA CZYSZCZENIA</div></a>';
				echo '<div class="sss"></div>';
				echo '<a href="user/profil.php"><div class="ss">PROFIL</div></a>';
				echo '<a href="admin/panel.php"><div class="ss">WIADOMOSCI</div></a>';
				echo '<a href="#" id="lg-out"><div class="ss">LOGOUT</div></a>';
				echo '</div>';
?>		 
